services:
  rupn-server:
    image: makame/rupn-server:latest
    container_name: rupn-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - rupn-server-state:/var/lib/rupn-server

volumes:
  rupn-server-state:
